{{- if .Values.namespaceCreate | default false }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "seraphc2.labels" . | nindent 4 }}
    name: {{ .Release.Namespace }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}