apiVersion: v1
kind: Service
metadata:
  name: {{ include "seraphc2.fullname" . }}
  labels:
    {{- include "seraphc2.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "seraphc2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application

{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seraphc2.postgresql.fullname" . }}
  labels:
    {{- include "seraphc2.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-service
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "seraphc2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}

{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seraphc2.redis.fullname" . }}-master
  labels:
    {{- include "seraphc2.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache-service
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "seraphc2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
{{- end }}

---
# Headless service for StatefulSet (if needed for clustering)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seraphc2.fullname" . }}-headless
  labels:
    {{- include "seraphc2.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless-service
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.config.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seraphc2.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application