apiVersion: v1
kind: ConfigMap
metadata:
  name: seraphc2-config
  namespace: seraphc2
  labels:
    app.kubernetes.io/name: seraphc2
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: seraphc2
data:
  NODE_ENV: 'production'
  PORT: '3000'
  HOST: '0.0.0.0'
  HTTPS_PORT: '8443'
  DB_HOST: 'postgres-service'
  DB_PORT: '5432'
  DB_NAME: 'seraphc2'
  DB_USER: 'seraphc2'
  DB_SSL: 'false'
  DB_POOL_MIN: '2'
  DB_POOL_MAX: '10'
  REDIS_HOST: 'redis-service'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  LOG_LEVEL: 'info'
  LOG_FILE_ENABLED: 'true'
  LOG_FILE_PATH: '/app/logs/seraphc2.log'
  LOG_MAX_SIZE: '10485760'
  LOG_MAX_FILES: '5'
  CORS_CREDENTIALS: 'true'
  RATE_LIMIT_WINDOW_MS: '900000'
  RATE_LIMIT_MAX_REQUESTS: '100'
  RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS: 'false'
  MAX_FILE_SIZE: '10485760'
  UPLOAD_PATH: '/app/uploads'
  ENABLE_METRICS: 'true'
  METRICS_PORT: '9090'
  HEALTH_CHECK_ENABLED: 'true'
  CLUSTER_MODE: 'false'
  WORKER_PROCESSES: '0'
  KEEP_ALIVE_TIMEOUT: '65000'
  BODY_PARSER_LIMIT: '1mb'
  HSTS_MAX_AGE: '31536000'
  CSP_POLICY: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' ws: wss:; frame-ancestors 'none';"
  BACKUP_ENABLED: 'true'
  BACKUP_SCHEDULE: '0 2 * * *'
  BACKUP_RETENTION_DAYS: '30'
  BCRYPT_ROUNDS: '12'
  SESSION_TIMEOUT: '3600'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: seraphc2
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: seraphc2
data:
  POSTGRES_DB: 'seraphc2'
  POSTGRES_USER: 'seraphc2'
  POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: seraphc2
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: seraphc2
data:
  redis.conf: |
    # Redis Production Configuration for SeraphC2 on Kubernetes

    # Network and Security
    bind 0.0.0.0
    protected-mode yes
    port 6379

    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Persistence
    save 900 1
    save 300 10
    save 60 10000

    # Disable dangerous commands in production
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command KEYS ""
    rename-command CONFIG "CONFIG_b835c3f8a5d9e7f2"
    rename-command DEBUG ""
    rename-command EVAL ""
    rename-command SHUTDOWN SHUTDOWN_b835c3f8a5d9e7f2

    # Logging
    loglevel notice
    logfile ""

    # Performance
    tcp-keepalive 300
    timeout 0
    tcp-backlog 511

    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Latency monitoring
    latency-monitor-threshold 100

    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60

    # Security
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes

    # Disable Lua debugging
    lua-time-limit 5000

    # Set the number of databases
    databases 16

    # Append only file
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes

    # HyperLogLog
    hll-sparse-max-bytes 3000
