apiVersion: v1
kind: Namespace
metadata:
  name: seraphc2
  labels:
    name: seraphc2
    app.kubernetes.io/name: seraphc2
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: seraphc2
  annotations:
    description: 'SeraphC2 Command and Control Framework'
